server:
  servlet:
    context-path: /api
spring:
  application:
    name: billy
  datasource:
    url: jdbc:mysql://localhost:3306/billy
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    user: root
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'